name: Fetch NSE Indices Daily with Puppeteer Stealth

on:
  schedule:
    - cron: '30 10 * * 1-5'  # 4:00 PM IST Mon-Fri (10:30 AM UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Puppeteer Extra and Stealth plugin with puppeteer
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run NSE Puppeteer stealth scraper
        run: node nse_puppeteer_stealth_scraper.js

      - name: Commit & push CSV if changed
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add data/all_indices.csv data/old_indices.csv || true

          git diff --cached --exit-code \
            || git commit -m "chore: update NSE index data via Puppeteer stealth"

          git push origin HEAD:main
