name: Fetch NSE Indices Daily

on:
  schedule:
    - cron: '30 10 * * 1-5'  # 4:00 PM IST Mon–Fri
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install nsepython pandas

      - name: Run downloader
        run: python nifty_downloader.py

      - name: Commit & push CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data/*.csv
          git commit -m "chore: update NSE indices" || echo "No changes"
          git push
